import { Inter } from "next/font/google";
import "./globals.css";
import MovieHeader from "@/Components/MovieHeader";
import Navbar from "@/Components/Navbar";
import SearchBox from "@/Components/SearchBox";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movie",
  description: "Generated by yujeong jang",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MovieHeader />
        <Navbar />
        <SearchBox />
        {children}
      </body>
    </html>
  );
}
