import { Inter } from "next/font/google";
import "./globals.css";
import ShopHeader from "@/Components/ShopHeader";
import Menus from "@/Components/Menus";
import ShopFooter from "@/Components/ShopFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next demo",
  description: "Generated by yujeong jang",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menus />
        <ShopHeader />
        {children}
        <ShopFooter />
      </body>
    </html>
  );
}
